apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-system-platforms-crk8s
  # namespace: crk8s-system
data:
  platform_defs.json: |-
    [
      {
        "version": "envds.apps.sampling-system/v1",
        "kind": "Platform",
        "metadata": {
          "name": "CRK83Payload01",
          "platform_type": "MSPPayload",
          "owner": "Local",
          "description": "",
          "contacts": [
            ""
          ]
        },
        "revision-time": "2025-10-01T00:00:00Z",
        "interface": {
          "power-input": [
            "input-24v-ups",
            "input-24v",
            "input-110v"
          ],
          "network": [
            "internal",
            "external"
          ],
          "sample-input": [
            "sample-line-01"
          ]
        }
      }
    ]