apiVersion: v1
kind: ConfigMap
metadata:
  name: parkerhannifin-btxconnect-config
  # namespace: msp
  labels:
    app: parkerhannifin-btxconnect
data:
  namespace_prefix: mspbase01
  envds_env_id: mspbase01
  operational.conf: |
    serial_number: "sn"
    daq_id: mspbase01
    interfaces:
      # default: serial
      default: # to read pump speed
        interface_env_id: mspbase01 # if omitted, defaults to envds_id of sensor
        interface_id: LabJack::Tx::ljtx207 
        path: counter-1
      pump_speed_sp: # to set pump speed
        interface_env_id: mspbase01 # if omitted, defaults to envds_id of sensor
        interface_id: LabJack::Tx::ljtx207 
        path: pwm-6

    settings:
      pump_speed_sp: 0 # initialize with pump set to off

      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
    #   pump_power: 1
    #   q_target: 300