apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sampling-states

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
# - sampling-states-deployment.yaml
# - sampling-states-service.yaml
- sampling-states-service_knative.yaml
# - sampling-states-ingress.yaml
# - sampling-states-triggers.yaml