apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kippzonen-splite2

namespace: mspbase02-hardware
# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: shelly-shellypro3
#     variant: test

resources:
- ../../base
- SPLite2-configmap.yaml

nameSuffix: "-742"
# patchesStrategicMerge:
#   - deployment.yaml

patches:
  # change configmap names to account for s/n suffix
  - target:
      kind: Deployment
      name: kippzonen-splite2
    patch: |-
      - op: replace 
        path: /spec/template/spec/volumes/0/configMap/name
        value: kippzonen-splite2-config-742
      - op: replace 
        path: /spec/template/spec/volumes/1/configMap/name
        value: sensor-definition-742
