apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  # namespace: msp-system
  labels:
    app: mqtt
  # namespace: envds-base
data:
  mosquitto.conf: |
    sys_interval 1
    autosave_interval 1
    allow_anonymous true
    autosave_on_changes true
    # logs
    log_dest stdout
    log_type all
    log_timestamp true
    log_timestamp_format %Y-%m-%d_%H:%M:%S
    connection_messages true
    # data
    persistence true
    persistence_location /mosquitto/data
    persistence_file mosquitto.db

    # Non-TLS
    listener 1883
    protocol mqtt

    # # Bridge
    # # connection pmel-dev_aws-iot-core_bridge
    # # address 10.55.169.210:8883
    # # remote_clientid payload01_mspbase01_bridge
    # connection crk8s_aws-iot-core_bridge
    # address iot.pmel-dev.oarcloud.noaa.gov:443
    # # address ayfar3nvv1l0l.iot.us-east-1.amazonaws.com:443
    # remote_clientid mspbase02_aws-iot-core_bridge
    # # remote_clientid pmel-dev-server
    # # bridge_protocol_version mqttv311
    # # bridge_protocol_version mqttv50
    # bridge_insecure false
    # # cleansession true
    # try_private false
    # start_type automatic
    # # notifications false

    # topic envds/+/sensor/+/data/update in 0 "" ""
    # # # # # topic envds/+/sensor/+/settings/update out 0 "" ""
    # # # # # topic envds/+/sensor/+/settings/request in 0 "" ""
    # # # # # topic envds/+/sensor/+/status/update in 0 "" ""
    # # # # # topic envds/+/sensor/+/status/request both 0 "" ""
    # # # # # topic envds/+/sensor/registry/update in 0 "" ""
    # # # # topic envds/+/device-instance/registry/update in 0 "" ""
    # # # topic main/envds/+/registry/sync-bcast in 0 "" ""
    # # # topic main/envds/+/registry/sync-update in 0 "" ""
    # # # topic main/envds/+/registry/sync-request in 0 "" ""
    # # # topic server/envds/+/registry/sync-bcast out 0 "" ""
    # # # topic server/envds/+/registry/sync-update out 0 "" ""
    # # # topic server/envds/+/registry/sync-request out 0 "" ""
    # # # # topic envds/controller/settings/request both 0 "" ""
    # # # # topic envds/device/settings/request both 0 "" ""
    # # # # topic envds/sensor/settings/request both 0 "" ""
    # # # # # # topic envds/sensor/settings/update both 0 "" ""
    # # # # # topic envds/payload01/controller/+/settings/update out 0 "" ""
    # # # # topic envds/+/controller/settings/update out 0 "" ""
    # # # # topic envds/+/controller-instance/registry/update in 0 "" ""
    # # # # topic envds/+/controller/+/controller/data/update in 0 "" ""
    # # # # # # topic envds/+/controller-definition/registry/update out 0 "" ""

    # # Certificate-based authentication
    # bridge_cafile /certs/rootCA.crt
    # bridge_certfile /certs/cert.crt
    # bridge_keyfile /certs/private.key
    # # tls_version tlsv1.2

    # # TLS ALPN
    # bridge_alpn "x-amzn-mqtt-ca"

    # # TLS
    # # https://mosquitto.org/man/mosquitto-tls-7.html
    # listener 8883
    # protocol mqtt
    # cafile /certs/ca.crt
    # certfile /certs/server.crt
    # keyfile /certs/server.key
    # require_certificate false