apiVersion: v1
kind: ConfigMap
metadata:
  name: kn-mqtt-adapter
  # namespace: msp-system
data:
  # mqtt_bridge_host: "0.0.0.0"
  # mqtt_bridge_port: 80
  knative_broker: "http://broker-ingress.knative-eventing.svc.cluster.local/payload02-system/default"

  mqtt_broker: "mqtt.payload02-system"
  mqtt_port: "1883"
  # mqtt_topic_filter: "instrument/#"
  mqtt_topic_subscriptions: >
    main/envds/+/registry/sync-bcast,
    main/envds/+/registry/sync-update,
    main/envds/+/registry/sync-request,
    envds/payload02/device-definition/registry/update,
    envds/payload02/device-instance/registry/update,
    envds/payload02/controller-definition/registry/update,
    envds/payload02/controller-instance/registry/update,
    envds/+/+/+/status/update,
    envds/+/+/+/settings/update,
    envds/+/+/+/control/update,
    envds/+/+/+/registry/update,
    envds/controller/settings/update,
    envds/+/controller/settings/update,
    envds/+/controller/registry/update,
    envds/sensor/settings/update,
    envds/+/sensor/settings/update

# old subscriptions:
# envds/+/+/+/registry/update
    # envds/+/+/+/data/update,   
    # envds/+/+/+/controller/data/update,   

  # mqtt_broker: "mosquitto.default"
  # mqtt_port: "1883"
  # # mqtt_topic_filter: "sensor/#"
  # mqtt_topic_subscription: "test-account/uas-test/#"

  # mqtt_broker: "iot.pmel-dev.oarcloud.noaa.gov"
  # mqtt_port: "8883"
  # # mqtt_topic_filter: "sensor/#"
  # # mqtt_topic_subscription: "test-account/uas-test/#"
  # mqtt_topic_subscription: "uasdaq/#"
