apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sampling-conditions

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
# - sampling-conditions-deployment.yaml
# - sampling-conditions-service.yaml
- sampling-conditions-service_knative.yaml
# - sampling-conditions-ingress.yaml
# - sampling-conditions-triggers.yaml