apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  # namespace: msp-system
  labels:
    app: mqtt
  # namespace: envds-base
spec:
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        # image: localhost:5000/envds/eclipse-mosquitto:2.0.14
        # image: envds-registry:36301/eclipse-mosquitto:2.0.14
        # image: envds-registry:5000/core/eclipse-mosquitto:2.0.14
        # image: envds-registry:5000/core/eclipse-mosquitto:2.0.15
        # image: registry-msp:5000/msp/eclipse-mosquitto:2.0.21
        image: eclipse-mosquitto:2.0.21
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 1883
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: mqtt-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-storage
              mountPath: /mosquitto/data
            - name: mosquitto-certs
              mountPath: /certs/rootCA.crt
              subPath: AmazonRootCA1.pem
            - name: mosquitto-certs
              mountPath: /certs/cert.crt
              subPath: device-certificate
            - name: mosquitto-certs
              mountPath: /certs/private.key
              subPath: private-key
      volumes:
        - name: mqtt-config
          configMap:
            name: mqtt-config
        - name: mosquitto-storage
          persistentVolumeClaim:
            claimName: mqtt-pvc
        - name: mosquitto-certs
          secret:
            secretName: aws-iot-credentials

