apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: datastore

# set namespace
namespace: pmel-dev-system

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

# resources:
# # Example configuration for the webserver
# # at https://github.com/monopole/hello
#   nameSuffix: -usc206
#   commonLabels:
#     app: usconverters-uscdr301
#     variant: test

resources:
- ../../base
- datastore-configmap.yaml
- datastore_db_password_sealed.yaml
# - ghcr-secret-msp-system-sealed.yaml
- datastore-triggers.yaml

# patchesStrategicMerge:
# - patch-service_knative.yaml

patches:
  # change configmap names to account for s/n suffix
  # - target:
  #     kind: Service
  #     name: datastore
  #   patch: |-
  #     - op: add 
  #       path: /spec/template/spec/containers/0/env
  #       name: DATASTORE_DB_USERNAME
  #       valueFrom: 
  #         configMapKeyRef:
  #           name: datastore
  #           key: db_username
  # - op: add 
  #   path: /spec/template/spec/containers/0/env
  #   name: DATASTORE_DB_PASSWORD
  #   secretKeyRef:
  #     name: db_password_secret
  #     key: db_password  
  - path: datastore-service_knative.yaml
    target: 
      kind: Service
      name: datastore
  # - target:
  #     kind: Trigger
  #     # name: default
  #   patch: |-
  #     - op: replace 
  #       path: /spec/broker
  #       value: kafka-broker


# patches:
#   - patch: |-
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: REPLACED_DURING_PATCH
#       spec:
#         template:
#           spec:
#             containers:
#               - name: webhook
#                 env:
#                   - name: WEBHOOK_DISABLE_NAMESPACE_OWNERSHIP
#                     value: "true"
#     target:
#       group: apps
#       kind: Deployment
#       name: ".*webhook.*"