apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mqtt-bridge

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
# - kn-mqtt-deployment.yaml
# - kn-mqtt-service.yaml
- mqtt-bridge-service_knative.yaml
# - kn-mqtt-ingress.yaml