apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: phoenixcontact-ntp

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
- ntp-deployment.yaml
- ntp-service.yaml

configMapGenerator:
  - name: sensor-definition
    files:
      - PhoenixContact_NTP_sensor_definition.json